### ISSUE TITLE
initialize value of signals with "="

### ISSUE THREAD

**Issue by bigtree7997** [jamieiles/uart#2]
It is not okay to just initialize the reg type signals with "=" at the beginning. It is thinking in software coding. Instead, you'll need to add an asynchronous reset to the module and intiailize all the sequential elements to an initial value.

**Comment by jamieiles** [comment]
This is a minimal UART without a reset designed for use in an FPGA where no asynchronous reset is required and so initial values are fine and use fewer resources than an async reset.
